### ISSUE TITLE
No Streaming 

### ISSUE THREAD

**Issue by nikhil96widhani** [parker1992/iptv-proxy#9]
Hi there, Great project but unfortunately i cannot stream URL. For my usecase i dont want to use a VPN because i have a cloud server and i want to proxy urls from my server ip instead of a vpn container. Please help related to what i am missing

my docker compose is 
```
version: "3.3"
services:
    iptv_proxy:
        image: parkerr1992/iptv-proxy
        container_name: iptv_proxy
        restart: unless-stopped
    # network_mode: service:nordlynx
        ports:
            - 8080:8080
        environment:
            - M3U_LOCATION=https://some/main.m3u
            # Required. Either a path or URL.
            - RELOAD_INTERVAL_MIN=60 # Not required and defaults to 60. This is used to update the /static directory with the latest m3u file.
            - LISTEN_PORT=8080

```

**Comment by parker1992** [comment]
Can you please advise what error you’re getting? And how do you access the proxy? Are you passing port 8080 in your video player?

**Comment by nikhil96widhani** [comment]
Problem is that the url gives empty playlist for me. Like its plane white page and nothing downloads when i open in browser vlc fails to get stream too. And yes i am passing the port 8080. But failing to check where its going wrong

**Comment by parker1992** [comment]
Can you try adding the environment variable below?

USE_HTTPS=True

**Comment by nikhil96widhani** [comment]
Are you sure? Because i am not using https on my server?

**Comment by parker1992** [comment]
Let me reproduce this tomorrow. I think I may have a regex issue on this line that may be incorrectly replacing your url with http instead of the original stream url which is https.

https://github.com/parker1992/iptv-proxy/blob/24c42f6f70424b4e9fb39501e333611f11cade24/parser.py#L42

**Comment by parker1992** [comment]
Let me try to reproduce this issue tomorrow when I’m on my computer. I think there’s an issue somewhere relating to https.

If you ssh into the container, are you able to curl the original m3u file?

**Comment by parker1992** [comment]
Try setting the config below:

M3U_PORT=8080

There's a bug where if this is blank, the new m3u will replace the urls with http://[address]/proxy/stream/... instead of http://[address]:8080/proxy/stream/...

Let me know if this works.

**Comment by nikhil96widhani** [comment]
Thanks for this. I will try this on Friday and report back.

**Comment by parker1992** [comment]
No problem. I'm fairly convinced this should work. According to the link below, I made this as a feature:

https://github.com/parker1992/iptv-proxy/blob/24c42f6f70424b4e9fb39501e333611f11cade24/config.ini#L9-L10

I just failed to update the README when I created this config. I'll update it now.

**Comment by nikhil96widhani** [comment]
I am still following this issue. I have been busy lately and will test and revert soon. Sorry about the delay.

**Comment by nikhil96widhani** [comment]
Hello still there is some issue now the m3u works but it fails to add the hostname in the m3u file.

the streaming url in the m3u is as follows: http://:8080/stream/url.mdp

my new docker file is 
```                                                                                        
version: "3.3"
services:
    iptv_proxy:
        image: parkerr1992/iptv-proxy
        container_name: iptv_proxy
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - M3U_LOCATION=https:/blahbalh.m3u
            - RELOAD_INTERVAL_MIN=60 # Not required and defaults to 60. This is used to update the /static directory with the latest m3u file.
            - LISTEN_PORT=8080
            - M3U_PORT=8080 # The port to add to the m3u file. If the app is running on port 80, you may not need this.

```
